name: Pipeline
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #At 00:00 everyday UTC ~ 7:00 everyday UTC+7

jobs:
  get_houses_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run get_house.py
          python dags/code/get_house.py

      - name: Run get_house_info.py
          python dags/code/get_house_info.py

      - name: Run preprocesing.py
          python dags/code/Preprocessing.py
        
      - name: Run overpass.py
          python dags/code/overpass.py

      